### ISSUE TITLE
windows下用npm安裝時產生error

### ISSUE THREAD

**Issue by esp10mm** [Canner/canner#34]
error MSB3428: Could not load the Visual C++ component "VCBuild.exe". 
可參考這篇:
http://stackoverflow.com/questions/17496189/error-in-installing-node-js-module-using-npm

將VCBuild.exe的目錄加入環境變數後可解決但又產生error
error C1083: Cannot open include file: 'winsock2.h': No such file or directory 

參考這篇後沒有解決我就沒再試了:
http://stackoverflow.com/questions/3623129/winsock2-h-no-such-file-or-directory

**Comment by chihsuan** [comment]
這個issue看起來不是我們能solve的。
